[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_ENV = "production"

[functions]
  external_node_modules = ["express", "bcryptjs", "jsonwebtoken", "better-sqlite3", "cors"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
